[package]
name = "humte"
version = "0.1.0"
authors = ["Carl Scherer"]
edition = "2018"

[dependencies]
dht22_pi = "0.3.0"
chrono = "0.4.11"
plotters = { version = "0.2.15", default_features = false, features = ["svg", "datetime", "line_series"] }
tiny_http = "0.7.0"
